### ISSUE TITLE
Compat with EMI and REI

### ISSUE THREAD

**Issue by solonovamax** [Anxxitty/farmers-delight-JEI-plugin#2]
Don't hard depend on JEI, so that this can also be loaded with EMI or REI

(Basically, just remove [this](https://github.com/Anxxitty/Just-Enough-Farmers-Recipes/blob/1.18/src/main/resources/fabric.mod.json#L35) line.)

**Comment by Anxxitty** [comment]
But in what context would you need to load this mod without JEI ? Or with any other recipe manager ?

**Comment by solonovamax** [comment]
eg. I might want to use REI.

REI does not provide a mod with an id `jei`, therefor this mod will fail to load.

adding JEI as well as REI causes *two* item lists to be displayed. it *is* being loaded with another recipe manager, that recipe manager being either REI or EMI, however they do not provide the JEI mod.

**Comment by Anxxitty** [comment]
I may be misunderstanding this as I dont use EMI or REI but why would you want my mod along with REI ? Farmer's Delight for fabric natively supports REI, and my mod only implements the recipes for JEI

**Comment by solonovamax** [comment]
ah, I see

nvm then, I was under the impression it didn't.

also, looking at farmer's delight, it seems to now offer native JEI support: https://github.com/vectorwing/FarmersDelight/blob/1.20/src/main/java/vectorwing/farmersdelight/integration/jei/JEIPlugin.java

**Comment by Anxxitty** [comment]
@solonovamax 
This is the repository for the Forge version of Farmer's Delight.
Farmer's Delight on Forge supports JEI,
but the Fabric version (https://github.com/newhoryzon/farmers-delight-fabric) only supports REI as of today.

**Comment by solonovamax** [comment]
ah, I see
