### ISSUE TITLE
Compatibility with Farmer's Delight Refabricated

### ISSUE THREAD

**Issue by 22luminary** [Anxxitty/farmers-delight-JEI-plugin#3]
The [Farmer's Delight mod](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric) used by this mod has been depricated. Please add support for the new mod, [Farmer's Delight Refabricated](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-refabricated).

**Comment by Anxxitty** [comment]
Farmer's Delight Refabricated supports JEI by default, therefore I will stop updating this mod and will not support Farmer's Delight Refabricated.
